back_Django_closing/blog/blog/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/post/', include('post.urls')),
    path('api/note/', include('note.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

back_Django_closing/blog/note/urls.py
from django.urls import path
from .views import *

app_name="note"
urlpatterns = [
		path('create', create_note, name='create'),
		path('delete/<int:note_pk>', delete_note),
		path('list/<str:category_name>/<int:page>', get_note_list),
		path('search/<str:query_string>/<int:page>', search_note),
		path('detail/<int:note_pk>', get_note_detail),
		path('category/', get_category_list),
]

back_Django_closing/blog/post/urls.py
from django.urls import path
from .views import *

app_name="post"
urlpatterns = [
		path('create', create_post, name='create'),
		path('delete/<int:post_pk>', delete_post),
		path('list/<str:category_name>/<int:page>', get_post_list),
		path('search/<str:query_string>/<int:page>', search_post),
		path('detail/<int:post_pk>', get_post_detail),
		path('category/', get_category_list),
]

back_Django_closing/blog/templates/create_note.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>글 작성</title>
	</head>
	<body>
		<form action={% url 'note:create' %} enctype="multipart/form-data" method="POST">
			{% csrf_token %}
			{{note_form.as_p}}
			{{upload_form.as_p}}
			<input type="submit" />
		</form>
	</body>
</html>

back_Django_closing/blog/templates/create_post.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>글 작성</title>
	</head>
	<body>
		<form action={% url 'post:create' %} enctype="multipart/form-data" method="POST">
			{% csrf_token %}
			{{post_form.as_p}}
			{{upload_form.as_p}}
			<input type="submit" />
		</form>
	</body>
</html>